export enum AppointmentStatus {
  PENDING_PAYMENT = "PENDING_PAYMENT",
  CONFIRMED = "CONFIRMED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  CANCELLED_BY_USER = "CANCELLED_BY_USER",
  CANCELLED_BY_DOCTOR = "CANCELLED_BY_DOCTOR",
  NO_SHOW = "NO_SHOW",
  IN_PROGRESS = "IN_PROGRESS",
  RESCHEDULE_PENDING = "RESCHEDULE_PENDING",
}
