export enum NotificationType {
  APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
  APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER",
  CONSULTATION_JOINED = "CONSULTATION_JOINED",
  CONSULTATION_REPORTS_ADDED = "CONSULTATION_REPORTS_ADDED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  SYSTEM = "SYSTEM",
  APPOINTMENT_RESCHEDULE_REQUESTED = "APPOINTMENT_RESCHEDULE_REQUESTED",
  APPOINTMENT_RESCHEDULED = "APPOINTMENT_RESCHEDULED",
}
