export enum TransactionType {
  APPOINTMENT_PAYMENT = "APPOINTMENT_PAYMENT",
  APPOINTMENT_REFUND = "APPOINTMENT_REFUND",
  WALLET_TOPUP = "WALLET_TOPUP",
  WITHDRAWAL = "WITHDRAWAL",
  DOCTOR_PAYOUT = "DOCTOR_PAYOUT",
  ADMIN_CORRECTION = "ADMIN_CORRECTION",
}
