export const ROUTES = {
  AUTH: {
    GOOGLE_AUTH: "/auth/google",
    SIGNUP: "/signup",
    RESEND_OTP: "/resend-otp",
    VERIFY_OTP: "/verify-otp",
    LOGIN: "/login",
    LOGOUT: "/logout",
    FORGOT_PASSWORD: "/forgot-password",
    FORGOT_PASSWORD_RESEND_OTP: "/forgot-password/resend-otp",
    FORGOT_PASSWORD_VERIFY_OTP: "/forgot-password/verify-otp",
    RESET_PASSWORD: "/reset-password",
    REFRESH_TOKEN: "/refresh",
    CHANGE_PASSWORD: "/change-password",
  },
  USER: {
    GET_USER_PROFILE: "/users/:id",
    GET_PROFILE_STAGE_1: "/users/profile/stage1",
    GET_PROFILE_STAGE_2: "/users/profile/stage2",
    GET_PROFILE_STAGE_3: "/users/profile/stage3",
    GET_PROFILE_STAGE_4: "/users/profile/stage4",
    SAVE_PROFILE_STAGE_1: "/users/profile/stage1",
    SAVE_PROFILE_STAGE_2: "/users/profile/stage2",
    SAVE_PROFILE_STAGE_3: "/users/profile/stage3",
    SAVE_PROFILE_STAGE_4: "/users/profile/stage4",
    GET_UPLOADED_DOCUMENTS: "/users/uploaded-documents",
    GET_UPLOADED_DOCUMENT: "/users/uploaded-documents/:id",
    CREATE_UPLOADED_DOCUMENT: "/users/uploaded-documents",
    UPDATE_UPLOADED_DOCUMENT: "/users/uploaded-documents/:id",
    DELETE_UPLOADED_DOCUMENT: "/users/uploaded-documents/:id",
  },
  DOCTOR: {
    GET_PUBLIC_DOCTORS: "/doctors/public",
    GET_PUBLIC_DOCTOR_PROFILE: "/doctors/:id/public-profile",
    GET_SPECIALIZATION_LIST: "/doctors/specialization-list",
    GET_DASHBOARD_TODAY: "/doctors/dashboard/today",
    GET_DASHBOARD_ANALYSIS: "/doctors/dashboard/analysis",
    GET_PROFILE_STAGE_1: "/doctors/profile/stage1",
    GET_PROFILE_STAGE_2: "/doctors/profile/stage2",
    GET_PROFILE_STAGE_3: "/doctors/profile/stage3",
    SAVE_PROFILE_STAGE_1: "/doctors/profile/stage1",
    SAVE_PROFILE_STAGE_2: "/doctors/profile/stage2",
    SAVE_PROFILE_STAGE_3: "/doctors/profile/stage3",
    RESUBMIT_PROFILE: "/doctors/profile/resubmit",
    GET_MEDICAL_LICENSE_UPLOAD_SIGNED_URL:
      "/doctors/profile/medical-license-upload-url",
    GET_DEGREE_CERTIFICATE_UPLOAD_SIGNED_URL:
      "/doctors/profile/degree-certificate-upload-url",
    GET_PROFILE_IMAGE_UPLOAD_SIGNED_URL: "/doctors/profile/image-upload-url",
    GET_BANNER_IMAGE_UPLOAD_SIGNED_URL: "/doctors/profile/banner-upload-url",
    GET_PROFILE_IMAGE_ACCESS_URL: "/doctors/profile/image-access-url",
    GET_BANNER_IMAGE_ACCESS_URL: "/doctors/profile/banner-access-url",
    GET_VERIFICATION_DOCS: "/doctors/profile/verification-docs",
    SAVE_VERIFICATION_DOCS: "/doctors/profile/verification-docs",
    GET_PRACTICE_LOCATIONS: "/doctors/practice-locations",
    GET_ALL_PRACTICE_LOCATIONS: "/doctors/all-practice-locations",
    GET_PRACTICE_DETAILS: "/doctors/practice",
    PRACTICE_DETAILS: "/doctors/practice",
    ONBOARDING_STEP_2: "/doctors/onboarding/step2",
    ONBOARDING_STEP_3: "/doctors/onboarding/step3",
    ONBOARDING_STEP_4: "/doctors/onboarding/step4",
    ONBOARDING_STEP_5: "/doctors/onboarding/step5",
    ONBOARDING_STEP_6: "/doctors/onboarding/step6",
    UPDATE_PROFILE_IMAGE: "/doctors/profile-image",
    UPDATE_BANNER_IMAGE: "/doctors/banner-image",
    GET_SIGNATURE_UPLOAD_URL: "/doctors/profile/signature-upload-url",
    SAVE_SIGNATURE: "/doctors/profile/signature",
    SAVE_REGISTRATION_NUMBER: "/doctors/profile/registration-number",
  },

  ADMIN: {
    DASHBOARD: {
      GET_STATS: "/admin/dashboard/stats",
    },
    USER_MANAGEMENT: {
      GET_USERS: "/admin/users",
      BLOCK_USER: "/admin/users/:id/block",
      UNBLOCK_USER: "/admin/users/:id/unblock",
      GET_USER_ANALYTICS: "/admin/users/:id/analytics",
    },
    DOCTOR_MANAGEMENT: {
      GET_DOCTORS: "/admin/doctors",
      GET_DOCTOR_PROFILE: "/admin/doctors/:id/profile",
      BLOCK_DOCTOR: "/admin/doctors/:id/block",
      UNBLOCK_DOCTOR: "/admin/doctors/:id/unblock",
      VERIFY_DOCTOR: "/admin/doctors/:id/verify",
      GET_DOCTOR_ANALYTICS: "/admin/doctors/:id/analytics",
    },
    APPOINTMENT_MANAGEMENT: {
      GET_APPOINTMENTS: "/admin/appointments",
      GET_APPOINTMENT: "/admin/appointments/:appointmentId",
    },
    SPECIALIZATION_MANAGEMENT: {
      ADD_SPECIALIZATION: "/admin/specializations",
      EDIT_SPECIALIZATION: "/admin/specializations",
      ACTIVATE_SPECIALIZATION: "/admin/specializations/activate/:id",
      DEACTIVATE_SPECIALIZATION: "/admin/specializations/deactivate/:id",
    },
    WALLET_MANAGEMENT: {
      GET_WALLETS: "/admin/wallets",
      GET_WALLET: "/admin/wallets/:id",
      GET_WALLET_TRANSACTIONS: "/admin/wallets/:id/transactions",
    },
    TRANSACTION_MANAGEMENT: {},
    PAYOUT_MANAGEMENT: {},
  },
  SPECIALIZATION: {
    GET_SPECIALIZATIONS: "/specializations",
  },
  SLOT: {
    GET_SLOTS: "/slots/:doctorId",
    CREATE_SLOT: "/slots",
    CREATE_RECURRING_SLOTS: "/slots/recurring",
    EDIT_SLOT: "/slots",
    DELETE_SLOT: "/slots/:id",
    BLOCK_SLOT: "/slots/:id/block",
    UNBLOCK_SLOT: "/slots/:id/unblock",
    GET_FULL_CALENDAR_SLOTS: "/slots/full-calendar",
    LOCK_SLOT: "/slots/:slotId/lock",
    BOOK_APPOINTMENT: "/slots/:slotId/book",
    GET_APPOINTMENT_SUMMARY: "/slots/:slotId/appointment-summary",
  },
  SCHEDULE_RULE: {
    GET_RULES: "/schedule-rules/doctor/:doctorId",
    CREATE_RULE: "/schedule-rules",
    EDIT_RULE: "/schedule-rules/:id",
    DELETE_RULE: "/schedule-rules/:id",
    TOGGLE_RULE: "/schedule-rules/:id/toggle",
  },
  DOCTOR_EXCEPTION: {
    GET_EXCEPTIONS: "/doctor-exceptions/doctor/:doctorId",
    CREATE_EXCEPTION: "/doctor-exceptions",
    DELETE_EXCEPTION: "/doctor-exceptions/:id",
    EDIT_EXCEPTION: "/doctor-exceptions/:id",
  },
  APPOINTMENT: {
    COMPLETE_APPOINTMENT: "/appointments/:appointmentId/complete",
    GET_PATIENT_APPOINTMENTS: "/appointments/patient",
    GET_PATIENT_APPOINTMENT: "/appointments/patient/:appointmentId",
    PREVIEW_CANCEL_APPOINTMENT: "/appointments/:appointmentId/cancel-preview",
    CANCEL_APPOINTMENT: "/appointments/:appointmentId/cancel",
    GET_DOCTOR_APPOINTMENTS: "/appointments/doctor",
    GET_DOCTOR_APPOINTMENT: "/appointments/doctor/:appointmentId",
    REQUEST_RESCHEDULE: "/appointments/:appointmentId/reschedule-request",
    ACCEPT_RESCHEDULE: "/appointments/:appointmentId/reschedule-accept",
    DECLINE_RESCHEDULE: "/appointments/:appointmentId/reschedule-decline",
  },
  ORGANIZATION: {
    LIST_ORGANIZATIONS: "/organizations",
    GET_ORGANIZATION_PROFILE: "/organizations/:id",
    BLOCK_ORGANIZATION: "/organizations/:id/block",
    UNBLOCK_ORGANIZATION: "/organizations/:id/unblock",
    ENROL_ORGANIZATION: "/organizations/enrol",
    CONFIRM_ENROLMENT: "/organizations/enrol/confirm",
    SEND_STATUS_OTP: "/organizations/status/otp",
    CHECK_STATUS: "/organizations/status/check",
    RESUBMIT_ENROLMENT: "/organizations/status/resubmit",
    GET_ORGANIZATION_BY_CODE: "/organizations/code/:code",
    ADMIN_LIST_ORGANIZATIONS: "/admin/organizations",
    ADMIN_GET_ORGANIZATION_BY_ID: "/admin/organizations/:id",
    ADMIN_UPDATE_ORGANIZATION_STATUS: "/admin/organizations/:id/status",
  },
  WEBHOOK: {
    STRIPE: "/stripe",
  },
  S3: {
    GET_DP_UPLOAD_SIGNED_URL: "/get-dp-upload-url",
    GET_HOSPITAL_REG_UPLOAD_SIGNED_URL:
      "/hospital/profile-registration-upload-url",
    GET_HOSPITAL_GST_UPLOAD_SIGNED_URL: "/hospital/profile-gst-upload-url",
    GET_DOCTOR_MEDICAL_LICENSE_UPLOAD_SIGNED_URL:
      "/doctor/profile-medical-license-upload-url",
    GET_DOCTOR_DEGREE_CERTIFICATE_UPLOAD_SIGNED_URL:
      "/doctor/profile-degree-certificate-upload-url",
    GET_DISPUTE_EVIDENCE_UPLOAD_SIGNED_URL:
      "/disputes/evidence-upload-url",
    GET_PATIENT_DOCUMENT_UPLOAD_SIGNED_URL:
      "/s3/patient-document-upload-url",
  },
  TRANSACTIONS: {
    GET_TRANSACTIONS: "/transactions",
    GET_TRANSACTION: "/transactions/:id",
    GET_USER_TRANSACTIONS: "/transactions/user",
    GET_DOCTOR_TRANSACTIONS: "/transactions/doctor",
  },
  WALLET: {
    GET_WALLET: "/wallet",
    ADD_MONEY_TO_WALLET: "/wallet/add-money",
  },
  CONSULTATION: {
    JOIN_CONSULTATION: "/consultations/join",
    END_CONSULTATION: "/consultations/end",
    CREATE_REPORT: "/consultations/reports",
    GET_REPORT_BY_APPOINTMENT_ID: "/consultations/reports/appointment/:appointmentId",
    GET_REPORT_BY_ID: "/consultations/reports/:id",
    LIST_REPORTS: "/consultations/reports",
    CREATE_PRESCRIPTION: "/consultations/prescriptions",
    GET_PRESCRIPTION_BY_APPOINTMENT_ID: "/consultations/prescriptions/appointment/:appointmentId",
    GET_PRESCRIPTION_BY_ID: "/consultations/prescriptions/:id",
    LIST_PRESCRIPTIONS: "/consultations/prescriptions",
    GET_MESSAGES: "/consultations/messages/room/:consultationId",
    SEND_MESSAGE: "/consultations/messages/room/:consultationId",
    EDIT_MESSAGE: "/consultations/messages/:messageId",
    DELETE_MESSAGE: "/consultations/messages/:messageId",
    MARK_MESSAGE_READ: "/consultations/messages/:messageId/read",
    GET_CHAT_UPLOAD_URL: "/consultations/messages/room/:consultationId/upload-url",
    GET_CHAT_ACCESS_URL: "/consultations/messages/file/:messageId/access-url",
    VERIFY_PRESCRIPTION: "/api/prescriptions/verify/:verificationToken",
    REVOKE_PRESCRIPTION: "/consultations/prescriptions/:id/revoke",
    GET_CHATS: "/consultations/chats",
  },

  REVIEW: {
    CREATE_OR_UPDATE: "/reviews",
    DELETE: "/reviews/:id",
    GET_BY_APPOINTMENT_ID: "/reviews/appointment/:appointmentId",
    GET_PUBLIC_DOCTOR_REVIEWS: "/reviews/doctor/:doctorId/public",
    DOCTOR_LIST: "/reviews/doctor",
    ADMIN_LIST: "/reviews/admin",
    ADMIN_DELETE: "/reviews/admin/:id",
  },
  PAYOUT: {
    GET_DOCTOR_PAYOUTS: "/payouts/doctor",
    GET_DOCTOR_PAYOUT_DETAILS: "/payouts/doctor/:id",
    GET_ADMIN_PAYOUTS: "/payouts/admin",
    GET_ADMIN_PAYOUT_DETAILS: "/payouts/admin/:id",
  },
  DISPUTES: {
    SUBMIT: "/disputes/submit",
    GET_BY_APPOINTMENT: "/disputes/appointment/:appointmentId",
    ADMIN_LIST: "/admin/disputes",
    ADMIN_DETAILS: "/admin/disputes/:id",
    ADMIN_UPDATE_STATUS: "/admin/disputes/:id/status",
    ADMIN_MODERATION: "/admin/users/:userId/moderation",
    ADMIN_FILE_ACCESS_URL: "/admin/disputes/file-access-url",
  },
};
