export const ROUTES = {
  AUTH: {
    GOOGLE_AUTH: "/auth/google",
    SIGNUP: "/signup",
    RESEND_OTP: "/resend-otp",
    VERIFY_OTP: "/verify-otp",
    LOGIN: "/login",
    LOGOUT: "/logout",
    FORGOT_PASSWORD: "/forgot-password",
    FORGOT_PASSWORD_RESEND_OTP: "/forgot-password/resend-otp",
    FORGOT_PASSWORD_VERIFY_OTP: "/forgot-password/verify-otp",
    RESET_PASSWORD: "/reset-password",
    REFRESH_TOKEN: "/refresh",
  },
  USER: {
    GET_USERS: "/users",
    GET_USER_PROFILE: "/users/:id",
    BLOCK_USER: "/users/:id/block",
    UNBLOCK_USER: "/users/:id/unblock",
    GET_PROFILE_STAGE_1: "/users/profile/stage1",
    GET_PROFILE_STAGE_2: "/users/profile/stage2",
    GET_PROFILE_STAGE_3: "/users/profile/stage3",
    GET_PROFILE_STAGE_4: "/users/profile/stage4",
    SAVE_PROFILE_STAGE_1: "/users/profile/stage1",
    SAVE_PROFILE_STAGE_2: "/users/profile/stage2",
    SAVE_PROFILE_STAGE_3: "/users/profile/stage3",
    SAVE_PROFILE_STAGE_4: "/users/profile/stage4",
  },
  DOCTOR: {
    GET_DOCTORS: "/doctors",
    GET_DOCTOR_PROFILE: "/doctors/:id",
    BLOCK_DOCTOR: "/doctors/:id/block",
    UNBLOCK_DOCTOR: "/doctors/:id/unblock",
    VERIFY_DOCTOR: "/doctors/:id/verify",
    GET_SPECIALIZATION_LIST: "/doctors/specialization-list",
    GET_PROFILE_STAGE_1: "/doctors/profile/stage1",
    GET_PROFILE_STAGE_2: "/doctors/profile/stage2",
    GET_PROFILE_STAGE_3: "/doctors/profile/stage3",
    SAVE_PROFILE_STAGE_1: "/doctors/profile/stage1",
    SAVE_PROFILE_STAGE_2: "/doctors/profile/stage2",
    SAVE_PROFILE_STAGE_3: "/doctors/profile/stage3",
    RESUBMIT_PROFILE: "/doctors/profile/resubmit",
    GET_MEDICAL_LICENSE_UPLOAD_SIGNED_URL:
      "/doctors/profile/medical-license-upload-url",
    GET_DEGREE_CERTIFICATE_UPLOAD_SIGNED_URL:
      "/doctors/profile/degree-certificate-upload-url",
    GET_VERIFICATION_DOCS: "/doctors/profile/verification-docs",
    SAVE_VERIFICATION_DOCS: "/doctors/profile/verification-docs",
    PRACTICE_DETAILS: "/doctors/practice",
    ONBOARDING_STEP_2: "/doctors/onboarding/step2",
    ONBOARDING_STEP_3: "/doctors/onboarding/step3",
    ONBOARDING_STEP_4: "/doctors/onboarding/step4",
    ONBOARDING_STEP_5: "/doctors/onboarding/step5",
    ONBOARDING_STEP_6: "/doctors/onboarding/step6",
  },
  SPECIALIZATION: {
    GET_SPECIALIZATIONS: "/specializations",
    ADD_SPECIALIZATION: "/specializations",
    EDIT_SPECIALIZATION: "/specializations",
    ACTIVATE_SPECIALIZATION: "/specializations/activate/:id",
    DEACTIVATE_SPECIALIZATION: "/specializations/deactivate/:id",
  },
  SLOT: {
    GET_SLOTS: "/slots",
    CREATE_SLOT: "/slots",
    CREATE_RECURRING_SLOTS: "/slots/recurring",
    EDIT_SLOT: "/slots",
    DELETE_SLOT: "/slots/:id",
  },
  ORGANIZATION: {
    LIST_ORGANIZATIONS: "/organizations",
    GET_ORGANIZATION_PROFILE: "/organizations/:id",
    BLOCK_ORGANIZATION: "/organizations/:id/block",
    UNBLOCK_ORGANIZATION: "/organizations/:id/unblock",
  },
  S3: {
    GET_DP_UPLOAD_SIGNED_URL: "/get-dp-upload-url",
    GET_HOSPITAL_REG_UPLOAD_SIGNED_URL:
      "/hospital/profile-registration-upload-url",
    GET_HOSPITAL_GST_UPLOAD_SIGNED_URL: "/hospital/profile-gst-upload-url",
    GET_DOCTOR_MEDICAL_LICENSE_UPLOAD_SIGNED_URL:
      "/doctor/profile-medical-license-upload-url",
    GET_DOCTOR_DEGREE_CERTIFICATE_UPLOAD_SIGNED_URL:
      "/doctor/profile-degree-certificate-upload-url",
  },
};
