export const ROUTES = {
  AUTH: {
    GOOGLE_AUTH: "/auth/google",
    SIGNUP: "/signup",
    RESEND_OTP: "/resend-otp",
    VERIFY_OTP: "/verify-otp",
    LOGIN: "/login",
    LOGOUT: "/logout",
    FORGOT_PASSWORD: "/forgot-password",
    FORGOT_PASSWORD_RESEND_OTP: "/forgot-password/resend-otp",
    FORGOT_PASSWORD_VERIFY_OTP: "/forgot-password/verify-otp",
    RESET_PASSWORD: "/reset-password",
    REFRESH_TOKEN: "/refresh",
  },
  USER: {
    GET_PROFILE_STAGE_1: "/profile-creation-1",
    GET_PROFILE_STAGE_2: "/profile-creation-2",
    GET_PROFILE_STAGE_3: "/profile-creation-3",
    GET_PROFILE_STAGE_4: "/profile-creation-4",
    SAVE_PROFILE_STAGE_1: "/profile-creation-1",
    SAVE_PROFILE_STAGE_2: "/profile-creation-2",
    SAVE_PROFILE_STAGE_3: "/profile-creation-3",
    SAVE_PROFILE_STAGE_4: "/profile-creation-4",
  },
  DOCTOR: {},
  HOSPITAL: {
    GET_PROFILE_STAGE_1: "/profile-creation-1",
    GET_PROFILE_STAGE_2: "/profile-creation-2",
    GET_PROFILE_STAGE_3: "/profile-creation-3",
    GET_PROFILE_STAGE_4: "/profile-creation-4",
    SAVE_PROFILE_STAGE_1: "/profile-creation-1",
    SAVE_PROFILE_STAGE_2: "/profile-creation-2",
    SAVE_PROFILE_STAGE_3: "/profile-creation-3",
    SAVE_PROFILE_STAGE_4: "/profile-creation-4",
  },
  ADMIN: {
    GET_SPECIALIZATIONS: "/specializations",
    ADD_SPECIALIZATION: "/specialization",
    EDIT_SPECIALIZATION: "/specialization/:id",
    ACTIVATE_SPECIALIZATION: "/specialization/activate/:id",
    DEACTIVATE_SPECIALIZATION: "/specialization/deactivate/:id",
  },
};
