export const ROUTES = {
  AUTH: {
    GOOGLE_AUTH: "/auth/google",
    SIGNUP: "/signup",
    RESEND_OTP: "/resend-otp",
    VERIFY_OTP: "/verify-otp",
    LOGIN: "/login",
    LOGOUT: "/logout",
    FORGOT_PASSWORD: "/forgot-password",
    FORGOT_PASSWORD_RESEND_OTP: "/forgot-password/resend-otp",
    FORGOT_PASSWORD_VERIFY_OTP: "/forgot-password/verify-otp",
    RESET_PASSWORD: "/reset-password",
    REFRESH_TOKEN: "/refresh",
    CHANGE_PASSWORD: "/change-password",
  },
  USER: {
    GET_USERS: "/users",
    GET_USER_PROFILE: "/users/:id",
    BLOCK_USER: "/users/:id/block",
    UNBLOCK_USER: "/users/:id/unblock",
    GET_PROFILE_STAGE_1: "/users/profile/stage1",
    GET_PROFILE_STAGE_2: "/users/profile/stage2",
    GET_PROFILE_STAGE_3: "/users/profile/stage3",
    GET_PROFILE_STAGE_4: "/users/profile/stage4",
    SAVE_PROFILE_STAGE_1: "/users/profile/stage1",
    SAVE_PROFILE_STAGE_2: "/users/profile/stage2",
    SAVE_PROFILE_STAGE_3: "/users/profile/stage3",
    SAVE_PROFILE_STAGE_4: "/users/profile/stage4",
  },
  DOCTOR: {
    GET_DOCTORS: "/doctors",
    GET_PUBLIC_DOCTORS: "/doctors/public",
    GET_DOCTOR_PROFILE: "/doctors/:id/profile",
    GET_PUBLIC_DOCTOR_PROFILE: "/doctors/:id/public-profile",
    BLOCK_DOCTOR: "/doctors/:id/block",
    UNBLOCK_DOCTOR: "/doctors/:id/unblock",
    VERIFY_DOCTOR: "/doctors/:id/verify",
    GET_SPECIALIZATION_LIST: "/doctors/specialization-list",
    GET_PROFILE_STAGE_1: "/doctors/profile/stage1",
    GET_PROFILE_STAGE_2: "/doctors/profile/stage2",
    GET_PROFILE_STAGE_3: "/doctors/profile/stage3",
    SAVE_PROFILE_STAGE_1: "/doctors/profile/stage1",
    SAVE_PROFILE_STAGE_2: "/doctors/profile/stage2",
    SAVE_PROFILE_STAGE_3: "/doctors/profile/stage3",
    RESUBMIT_PROFILE: "/doctors/profile/resubmit",
    GET_MEDICAL_LICENSE_UPLOAD_SIGNED_URL:
      "/doctors/profile/medical-license-upload-url",
    GET_DEGREE_CERTIFICATE_UPLOAD_SIGNED_URL:
      "/doctors/profile/degree-certificate-upload-url",
    GET_PROFILE_IMAGE_UPLOAD_SIGNED_URL: "/doctors/profile/image-upload-url",
    GET_BANNER_IMAGE_UPLOAD_SIGNED_URL: "/doctors/profile/banner-upload-url",
    GET_PROFILE_IMAGE_ACCESS_URL: "/doctors/profile/image-access-url",
    GET_BANNER_IMAGE_ACCESS_URL: "/doctors/profile/banner-access-url",
    GET_VERIFICATION_DOCS: "/doctors/profile/verification-docs",
    SAVE_VERIFICATION_DOCS: "/doctors/profile/verification-docs",
    GET_PRACTICE_LOCATIONS: "/doctors/practice-locations",
    GET_ALL_PRACTICE_LOCATIONS: "/doctors/all-practice-locations",
    GET_PRACTICE_DETAILS: "/doctors/practice",
    PRACTICE_DETAILS: "/doctors/practice",
    ONBOARDING_STEP_2: "/doctors/onboarding/step2",
    ONBOARDING_STEP_3: "/doctors/onboarding/step3",
    ONBOARDING_STEP_4: "/doctors/onboarding/step4",
    ONBOARDING_STEP_5: "/doctors/onboarding/step5",
    ONBOARDING_STEP_6: "/doctors/onboarding/step6",
    GET_TRANSACTIONS: "/doctors/transactions",
    UPDATE_PROFILE_IMAGE: "/doctors/profile-image",
    UPDATE_BANNER_IMAGE: "/doctors/banner-image",
  },
  SPECIALIZATION: {
    GET_SPECIALIZATIONS: "/specializations",
    ADD_SPECIALIZATION: "/specializations",
    EDIT_SPECIALIZATION: "/specializations",
    ACTIVATE_SPECIALIZATION: "/specializations/activate/:id",
    DEACTIVATE_SPECIALIZATION: "/specializations/deactivate/:id",
  },
  SLOT: {
    GET_SLOTS: "/slots/:doctorId",
    CREATE_SLOT: "/slots",
    CREATE_RECURRING_SLOTS: "/slots/recurring",
    EDIT_SLOT: "/slots",
    DELETE_SLOT: "/slots/:id",
    GET_FULL_CALENDAR_SLOTS: "/slots/full-calendar",
    LOCK_SLOT: "/slots/:slotId/lock",
    BOOK_APPOINTMENT: "/slots/:slotId/book",
    GET_APPOINTMENT_SUMMARY: "/slots/:slotId/appointment-summary",
  },
  APPOINTMENT: {
    COMPLETE_APPOINTMENT: "/appointments/:appointmentId/complete",
    GET_PATIENT_APPOINTMENTS: "/appointments/patient",
    GET_PATIENT_APPOINTMENT: "/appointments/patient/:appointmentId",
    PREVIEW_CANCEL_APPOINTMENT: "/appointments/:appointmentId/cancel-preview",
    CANCEL_APPOINTMENT: "/appointments/:appointmentId/cancel",
    GET_DOCTOR_APPOINTMENTS: "/appointments/doctor",
    GET_DOCTOR_APPOINTMENT: "/appointments/doctor/:appointmentId",
    GET_APPOINTMENTS: "/appointments",
    GET_APPOINTMENT: "/appointments/:appointmentId",
  },
  ORGANIZATION: {
    LIST_ORGANIZATIONS: "/organizations",
    GET_ORGANIZATION_PROFILE: "/organizations/:id",
    BLOCK_ORGANIZATION: "/organizations/:id/block",
    UNBLOCK_ORGANIZATION: "/organizations/:id/unblock",
  },
  WEBHOOK: {
    STRIPE: "/stripe",
  },
  S3: {
    GET_DP_UPLOAD_SIGNED_URL: "/get-dp-upload-url",
    GET_HOSPITAL_REG_UPLOAD_SIGNED_URL:
      "/hospital/profile-registration-upload-url",
    GET_HOSPITAL_GST_UPLOAD_SIGNED_URL: "/hospital/profile-gst-upload-url",
    GET_DOCTOR_MEDICAL_LICENSE_UPLOAD_SIGNED_URL:
      "/doctor/profile-medical-license-upload-url",
    GET_DOCTOR_DEGREE_CERTIFICATE_UPLOAD_SIGNED_URL:
      "/doctor/profile-degree-certificate-upload-url",
  },
  TRANSACTIONS: {
    GET_TRANSACTIONS: "/transactions",
    GET_TRANSACTION: "/transactions/:id",
    GET_USER_TRANSACTIONS: "/transactions/user",
    GET_DOCTOR_TRANSACTIONS: "/transactions/doctor",
  },
  WALLET: {
    GET_WALLET: "/wallet",
    ADD_MONEY_TO_WALLET: "/wallet/add-money",
  },
  ADMIN_WALLET: {
    GET_WALLETS: "/wallets",
    GET_WALLET: "/wallets/:id",
    GET_WALLET_TRANSACTIONS: "/wallets/:id/transactions",
  },
  CONSULTATION: {
    JOIN_CONSULTATION: "/consultations/join",
    END_CONSULTATION: "/consultations/end",
  },
  PAYOUTS: {
    GET_DOCTOR_PAYOUTS: "/payouts/doctor",
    GET_DOCTOR_PAYOUT_DETAILS: "/payouts/doctor/:id",
    GET_ADMIN_PAYOUTS: "/payouts/admin",
    GET_ADMIN_PAYOUT_DETAILS: "/payouts/admin/:id",
  },
};
